version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: poojakit
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://neondb_owner:npg_uoyRD2PAVWk7@ep-rapid-leaf-adj2cq2b-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      JWT_SECRET: 24c58951c0cb6bf925a6641f276f7fa6716c869a
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://backend:8080
    depends_on:
      - backend